In [3]:
import numpy as np

# numpy functions

In [10]:
 np.amin()   # minimum value of element along a specified axis.
 np.amax()   # maximum value of element along a specified axis.
 np.mean()   # find the mean
 np.median()  # find median value of data set.
 np.ptp()    # range of value along an axis  //Range = max value – min value.
 np.std()     # find standard distribution 
 np.var()      #find veriance
np.average()    #
np.percentile()

TypeError: _amin_dispatcher() missing 1 required positional argument: 'a'

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])   # create array from list

In [12]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
print(arr.ndim)    #dimantion of array

2


In [15]:
print(arr.shape)    #SHAPE OF ARRAY

(2, 4)


In [16]:
print(arr.data)      #memory location of array

In [17]:
print(type(arr))     #type of array

<class 'numpy.ndarray'>


In [18]:
a =10
id(a)       #memory location of variable

2385839221328

In [19]:
# in 2-D Array :
#axis = 0 (cloumn), =1(row)

In [20]:
b = np.array([[20,30,60],[25,26,27],[56,43,56]])
print(b,"\n")

[[20 30 60]
 [25 26 27]
 [56 43 56]] 



In [21]:
b.dtype     #datatype of array 

dtype('int32')

In [22]:
b.itemsize   #size of element (int = 4 byte)

4

In [23]:
b.size   #number of element in array

9

In [24]:
b.shape

(3, 3)

In [25]:
b = np.array([[20,21,22],[25,26,27],[56,43,56]],dtype = np.float64)   #convert element int into float

In [26]:
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize,"\n")

[[20. 21. 22.]
 [25. 26. 27.]
 [56. 43. 56.]] 

float64 

8 



In [27]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype = np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype = np.complex128)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize,"\n")

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16 



In [28]:
v = np.array(b,dtype = np.double)
print(v,"\n")
print(v.dtype,"\n")
print(v.itemsize,"\n")

[[20. 21. 22.]
 [25. 26. 27.]
 [56. 43. 56.]] 

float64 

8 



In [29]:
n = np.array(b,dtype = np.int32)
print(n,"\n")
print(n.dtype,"\n")
print(n.itemsize,"\n")

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

int32 

4 



In [30]:
print(np.sum(n))  #sum of all elements
print(np.sum(n,axis = 0))  #sum of elements in colums
print(np.sum(n,axis = 1))  #sum of elements in rows  0

296
[101  90 105]
[ 63  78 155]


In [31]:
print(np.amin(n))     # find minimum value in entire array
print(np.amin(n, axis = 0))   # minimum value in column vise of array
print(np.amin(n, axis = 1))     # minimum value in row vise of array

20
[20 21 22]
[20 25 43]


In [32]:
print(np.amax(n))        # find maximum value in entire array
print(np.amax(n, axis = 0))   # maximum value in column vise of array
print(np.amax(n, axis = 1))     # maximum value in row vise of array
print(type(n))

56
[56 43 56]
[22 27 56]
<class 'numpy.ndarray'>


In [33]:
print(np.mean(n))     # find mean value in entire array        #mean = sum of all element in array /  number of element in array
print(np.mean(n,axis = 0))   # mean value in column vise of array
print(np.mean(n,axis = 1))    # mean value in row vise of array
print(type(n))

32.888888888888886
[33.66666667 30.         35.        ]
[21.         26.         51.66666667]
<class 'numpy.ndarray'>


In [34]:
#median                       # first we write element in sorted from in line. ex. 20 21 22 25 26 27 43 56 56
print(np.median(n))          #median = arr[n/2] (if n number of arry is even)  = (arr[n-1/2] + arr[n+1/2])/2 (if n number of arry is odd)
print(np.median(n,axis = 0))
print(np.median(n,axis = 1))

26.0
[25. 26. 27.]
[21. 26. 56.]


In [35]:
#stadrand deviation              # std = sqr(var)
print(np.std(n))
print(np.std(n,axis =0))
print(np.std(n,axis =1))

13.907986869616757
[15.92342788  9.41629793 14.98888477]
[0.81649658 0.81649658 6.12825877]


In [36]:
#varience                           # varience = ((element[0]-mean)^2 + (element[1]-mean)^2 +...+(element[n]-mean)^2) / no. of element in array
print(np.var(n))                  
print(np.var(n,axis =0))
print(np.var(n,axis =1))

193.4320987654321
[253.55555556  88.66666667 224.66666667]
[ 0.66666667  0.66666667 37.55555556]


In [37]:
#average
print(np.average(n))           #  average = sum of all element in array /  number of element in array

32.888888888888886


In [38]:
r = np.array([2,3,4])
print(r)

[2 3 4]


In [39]:
#weighted average                        # weighted average = weighted value[0]*array value[0] + weighted value[1]*array value[1] +...+ weighted value[n]*array value[n] /  sum of all weights
w = np.array([4,5,6])                        # ex. weighted average = 2*4 + 3*5 + 4*6 /  4+5+6  = 3.13
print(w)
print(np.average(r,weights=w))

[4 5 6]
3.1333333333333333


In [44]:
#weighted average                        # weighted average = weighted value[0]*array value[0] + weighted value[1]*array value[1] +...+ weighted value[n]*array value[n] /  sum of all weights
n = np.array(b,dtype = np.int32)
print(n,"\n")
print(w,"\n")
print(np.average(n, weights=w, axis = 0))   # ex. weighted average = ( 20*4 + 25*5 + 56*6 / 4+5+6  = 36.0666 , 21*4 + 26*5 + 43*6 / 4+5+6 , 22*4 + 27*5 + 56*6 / 4+5+6 )

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

[4 5 6] 

[36.06666667 31.46666667 37.26666667]


In [46]:
n = np.array(b,dtype = np.int32)
print(n,"\n")
v = np.array(b,dtype = np.double)
print(v,"\n")
print(np.average(n, weights=v)) 
print(np.average(n, weights=v,axis = 0)) 

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

[[20. 21. 22.]
 [25. 26. 27.]
 [56. 43. 56.]] 

[41.1980198  32.95555556 41.41904762]


In [53]:
#percentile                            # np.percentile(arr,percentie,row or column)
print(r,"\n")                        # first we write sorted array in line then position = persentile*(n+1) / 100 where n=no. of elements
print(n,"\n")                                # percentile = arr[position]
print(np.percentile(r,60),"\n")        #ex. 60*(3+1) / 100 = 2.4  = arr[2.4]
print(np.percentile(r,6),"\n")
print(np.percentile(n,60),"\n")
print(np.percentile(n,10,0),"\n")
print(np.percentile(n,40,1),"\n")
print(np.percentile(n,6,1))

[2 3 4] 

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

3.2 

2.12 

26.8 

[21. 22. 23.] 

[20.8 25.8 53.4] 

[20.12 25.12 44.56]


In [56]:
#range                      # np.ptp = arr[end position] - arr[start position] 
print(r,"\n")
print(n,"\n")
print(np.ptp(r),"\n")
print(np.ptp(n,0),"\n")
print(np.ptp(n,1))

[2 3 4] 

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

2 

[36 22 34] 

[ 2  2 13]


In [48]:
#reshape of array
u = np.array([[1,2,3,4],[5,6,7,8]])
print(u,"\n")
print(u.reshape(4,2),"\n")
print(np.median(u))  

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

4.5


In [58]:
#slicing in array
print(n,"\n")

print(n[0,1],"\n")
print(n[2,1],"\n")
print(n[2,2],"\n")

[[20 21 22]
 [25 26 27]
 [56 43 56]] 

21 

43 

56 



# Stacking


In [11]:
d = np.arange(16).reshape(4,4)
print(d,"\n")

f = np.arange(12).reshape(3,4)
print(f,"\n")

h = np.arange(12).reshape(4,3)
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
f = np.arange(10,20).reshape(2,5)
print(f)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
print(np.vstack((d,f)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
print(np.hstack((d,h)))

[[ 0  1  2  3  0  1  2]
 [ 4  5  6  7  3  4  5]
 [ 8  9 10 11  6  7  8]
 [12 13 14 15  9 10 11]]


In [16]:
x = np.array([3,4,5,6,7,8,88])
y = np.array([5])
z = np.array([30,4,58,60,7,86,88])
print(x+y,"\n")
print(x+z,"\n")
print(x*y,"\n")
print(x/y,"\n")
print(x//y)

[ 8  9 10 11 12 13 93] 

[ 33   8  63  66  14  94 176] 

[ 15  20  25  30  35  40 440] 

[ 0.6  0.8  1.   1.2  1.4  1.6 17.6] 

[ 0  0  1  1  1  1 17]


In [17]:
print(np.zeros((4,3)),"\n")
print(np.ones((3,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
l1 = [[1,2,3],[4,3,6]]
vector1 = np.array(l1)
print(vector1)

[[1 2 3]
 [4 3 6]]


# matrixs

In [9]:
m1 = np.matrix("1 2;3 4")
print(m1)

[[1 2]
 [3 4]]


In [27]:
m2 = np.matrix([[1 ,2 ,3],[3, 4,8]])
print(m2)

[[1 2 3]
 [3 4 8]]


In [28]:
a = 10
print(np.dot(m2,a))

[[10 20 30]
 [30 40 80]]


In [32]:
m3 = np.matrix("4 5 ;6 7 ;9 8")
print(m3,"\n")
print(np.dot(m2,m3),"\n")
print(np.dot(m3,m2),"\n")


[[4 5]
 [6 7]
 [9 8]] 

[[ 43  43]
 [108 107]] 

[[19 28 52]
 [27 40 74]
 [33 50 91]] 

