# NumPy - Numerical Python Library

In [1]:
#Import Numpy Library

import numpy as np

In [2]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#diamension of the array

print(arr.ndim)

2


In [4]:
#shape of the array

print(arr.shape)

(2, 4)


In [5]:
#diamension of the array

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#diamension of the array

print(arr.data)

# Statistical Functions

In [4]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(b,"\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]] 



In [64]:
b.dtype

dtype('int32')

In [84]:
b.itemsize

4

In [85]:
b.size

9

In [86]:
b.shape

(3, 3)

In [4]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [107]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex128)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize)

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16


In [5]:
# sum value of an array
print(np.sum(b))

234.0


In [6]:
# sum value along a specified axis
print(b,"\n")
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

[75 78 81]
[63 78 93]


In [7]:
# Minimum Value
print(b,"\n")
print(np.amin(b))
print(np.amin(b,axis=0))
print(np.amin(b,axis=1))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

20
[20 21 22]
[20 25 30]


In [114]:
# Maximum Value
print(np.amax(b))
print(np.amax(b,axis=0))
print(np.amax(b,axis=1))
print(type(b))

32.0
[30. 31. 32.]
[22. 27. 32.]
<class 'numpy.ndarray'>


In [8]:
# Mean
print(b,"\n")
print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
print(type(b))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

26.0
[25. 26. 27.]
[21. 26. 31.]
<class 'numpy.ndarray'>


In [9]:
# Standatrd Deviation
print(b,"\n")
print(np.std(b))
print(np.std(b,axis=0))
print(np.std(b,axis=1))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

4.163331998932265
[4.0824829 4.0824829 4.0824829]
[0.81649658 0.81649658 0.81649658]


In [10]:
# Variance 
print(b,"\n")
print(np.var(b))
print(np.var(b,axis=0))
print(np.var(b,axis=1))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

17.333333333333332
[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]


In [118]:
# Weighted Average
print(np.average(b))

26.0


In [12]:
c = np.array([2,4,6, 1,3,5, 8,10,12, 7,9,11])
print(c)

[ 2  4  6  1  3  5  8 10 12  7  9 11]


In [120]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5 ]


In [121]:
print(np.average(c, weights=weight))

6.444444444444445


In [13]:
# Percentile
print(c,"\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(b,5,1))
print(np.percentile(b,5,0))
print(np.percentile(b,4,0))
print(np.percentile(b,4,1))

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

1.55
1.88
[20.1 25.1 30.1]
[20.5 21.5 22.5]
[20.4 21.4 22.4]
[20.08 25.08 30.08]


In [123]:
# Peak to peak
print(b,"\n")

print(c,"\n")

print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

11
[10. 10. 10.]
[2. 2. 2.]


In [24]:
print(b,"\n")
print(b.shape,"\n")
print(b.reshape(1,9),"\n")
print(b)

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

(3, 3) 

[[20 21 22 25 26 27 30 31 32]] 

[[20 21 22]
 [25 26 27]
 [30 31 32]]


# Slicing

In [131]:
e=[25,35,50,55,70,85,95]
print(e[0:4],"\n")
print(e[-1])

[25, 35, 50, 55] 

95


In [18]:
# 2 D Array
l=np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

70 

25 

[25 45] 

[62 66 68 70] 

[62 66] 



# Stacking

In [19]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12,24).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [23]:
print(d,"\n")
print(f,"\n")
print(np.hstack((d,f)),'\n')
print(np.hstack((f,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [21]:
print(d,"\n")
print(f,"\n")
print(np.vstack((d,f)),"\n")
print(np.vstack((f,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



# Mathematical Operations

In [46]:
x=np.array([2,8,10,35,55,60])
y=np.array([1,7,9,34,54,59])
print(x,"\n","\n")
print(y,"\n")
print(x+y,"\n")
print(x-y,"\n")
print(x*y,"\n")
print(x/y,"\n")
print(x//y)

[ 2  8 10 35 55 60] 
 

[ 1  7  9 34 54 59] 

[  3  15  19  69 109 119] 

[1 1 1 1 1 1] 

[   2   56   90 1190 2970 3540] 

[2.         1.14285714 1.11111111 1.02941176 1.01851852 1.01694915] 

[2 1 1 1 1 1]


In [99]:
print(np.zeros((4,3)),"\n")
print(np.ones((3,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


print(np.arange(1,5))
print(np.arange(1,20,2))

# Random Number Generator using numpy

In [3]:
from numpy import random
x= random.randint(100)
print(x)

22


In [8]:
#Generate Random Float

x= random.rand()
print(x)

0.6538887333987534


In [9]:
#3.	Generate Random Array

from numpy import random
x= random.randint(100, size=(5))
print(x)

[14 61 78 76 23]


In [10]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

from numpy import random
x= random.randint(100, size=(3, 5))
print(x)


[[ 2 76 87 96  7]
 [88 69 33 20  8]
 [ 1 60 81  3 15]]


# 2.4 PRACTICAL:  Creating scalars in Numpy

In [2]:
#numpy.asscaler()

import numpy as np

in_arr = np.array([8])

print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)
print("output scalar from input array ", out_scalar)


input array is  [8]
output scalar from input array  8


C:\Users\hp\AppData\Local\Temp/ipykernel_8852/417224096.py:9: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


# 2.5 PRACTICAL:  Creating Vector in Numpy

In [17]:
#import numpy

import numpy as np

#creating 1-D list
list1 = [1, 2, 3]

#creating 1-D list vertical

list2 = [[10],
        [20],
        [30]]

#create vector1

vector1 =  np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("------------------")

print("Vectical Vector")
print(vector2)



Horizontal Vector
[1 2 3]
------------------
Vectical Vector
[[10]
 [20]
 [30]]


# 2.6 PRACTICAL Creating Matrix in Numpy

In [18]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("via string input : \n", a, "\n\n")

#array-like input
b = np.matrix([[5, 6, 7], [4, 6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


# 2.7 PRACTICAL:  Matrix Multiplication in Numpy

In [19]:
import numpy as np

A = 5

B = [[6, 7],
      [8, 9]]
 
print(np.dot(A,B))

[[30 35]
 [40 45]]


In [20]:
import numpy as np

A = [[6, 7],
      [8, 9]]
      
B = [[1, 3],
      [5, 7]]

print(np.dot(A,B))

print("----------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
----------
[[30 34]
 [86 98]]


# 2.8 PRACTICAL:  Measure of Central Tendency Using Numpy

In [21]:
import numpy as np

arr = np.array([[1,23,78], [98,60,75],[79,25,48]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))


[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [28]:
#2.	Finding Mean, Median, Standard Deviation and Variance in NumPy
a = np.array([5,6,7])
print(a)
print("mean of array a =",np.mean(a))
print("median of array a =",np.median(a))
print("standard deviation of array a =",np.std(a))
print("Variance of array a =",np.var(a))

[5 6 7]
mean of array a = 6.0
median of array a = 6.0
standard deviation of array a = 0.816496580927726
Variance of array a = 0.6666666666666666


# 2.9 PRACTICAL:  Percentile & Interquartile in Numpy

In [2]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92,93, 96, 97,101,105,112,116]

#first quartile(Q1)

Q1 = np.median(data[:10])
print(Q1)

#third Quartile
Q3 = np.median(data[10:])
print(Q3)

#interquartile range

IQR = Q3-Q1

print(IQR)


62.5
96.5
34.0


# 2.10 PRACTICAL:  Array Broadcasting in Numpy

In [32]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

array([2., 4., 6.])

In [33]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])